services:
  - type: web
    name: ll-demand-planner-ws
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: CIN7_USER
        sync: false
      - key: CIN7_KEY
        sync: false
      - key: SHOPIFY_TOKEN
        sync: false
      - key: SHOPIFY_TOKEN_CUSHIE
        sync: false
      - key: SHOPIFY_TOKEN_LL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
